# Generated by Django 3.2.6 on 2021-08-15 23:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(db_column='car_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('miles_per_gallon', models.SmallIntegerField(null=True)),
                ('cylinders', models.SmallIntegerField(null=True)),
                ('displacement', models.SmallIntegerField(null=True)),
                ('horsepower', models.SmallIntegerField(null=True)),
                ('weight_in_lbs', models.SmallIntegerField(null=True)),
                ('acceleration', models.SmallIntegerField(null=True)),
                ('year', models.DateField(null=True)),
                ('origin', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
